import NewsCard from './NewsCard';

const Newsfeeds = () => {
  // Dummy data for display featured news items.
  // TODO: Replace with actual data from the backend.
  const dummyString50chrs =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ';

  const dummyNews = [
    {
      title: 'Article Title',
      image: 'https://via.placeholder.com/150',
      publicationDate: '2021-09-01',
      description: dummyString50chrs,
    },
    {
      title: 'Article Title',
      image: 'https://via.placeholder.com/150',
      publicationDate: '2021-09-01',
      description: 'Description',
    },
    {
      title: 'Article Title',
      image: 'https://via.placeholder.com/150',
      publicationDate: '2021-09-01',
      description: 'Description',
    },
  ];

  /**
   * Modified the styles generated by Vercel's v0.
   * @see https://v0.dev/t/Su3hBqYXCEI
   * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
   */
  return (
    <section className="pb-8 md:pb-16 lg:pb-24">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 xl:grid-cols-3">
          {dummyNews.map((news, index) => {
            return <NewsCard key={index} news={news} />;
          })}
        </div>
      </div>
    </section>
  );
};
export default Newsfeeds;
