import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { Button, Form, Alert } from 'react-bootstrap';
import { postUserSignup } from '../../utils/api';
import { useAuth } from '../../contexts/AuthContext';

const SignupForm = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const navigate = useNavigate();
  const { login } = useAuth();
  const [signupError, setSignupError] = useState('');

  const onSubmit = (userData) => {
    postUserSignup(userData, navigate, setSignupError, login);
  };

  /**
   * Modified the styles generated by Vercel's v0.
   * @see https://v0.dev/t/9I7fb3MwnuW
   * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
   */
  return (
    <div className="mx-auto sm:w-1/2 xl:w-1/3">
      <h1 className="font-bold text-center">Sign-up</h1>
      <Form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        <Form.Text className="text-gray-500">* Required fields</Form.Text>
        <Form.Group controlId="username">
          <Form.Label>Username*</Form.Label>
          <Form.Control
            type="text"
            {...register('username', { required: 'Username is required.' })}
          />
          {errors.username && (
            <p className="error">{errors.username.message}</p>
          )}
        </Form.Group>
        <Form.Group controlId="password">
          <Form.Label>Password*</Form.Label>
          <Form.Control
            type="password"
            {...register('password', { required: 'Password is required.' })}
          />
          {errors.password && (
            <p className="error">{errors.password.message}</p>
          )}
        </Form.Group>
        <Form.Group controlId="email">
          <Form.Label>Email*</Form.Label>
          <Form.Control
            type="email"
            {...register('email', { required: 'Email is required.' })}
          />
          {errors.email && <p className="error">{errors.email.message}</p>}
        </Form.Group>
        {signupError && (
          <Alert key="danger" variant="danger">
            {signupError}
          </Alert>
        )}
        <Button className="w-full" variant="dark" type="submit">
          Sign Up
        </Button>
      </Form>
    </div>
  );
};

export default SignupForm;
