# Generated by Django 5.0.1 on 2024-02-11 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=50)),
                ('breed', models.CharField(max_length=255)),
                ('disposition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('good_with_animals', 'Good with other animals'), ('good_with_children', 'Good with children'), ('leash_needed', 'Pet must be leashed at all times')], max_length=50), size=None)),
                ('picture_url', models.URLField()),
                ('availability', models.CharField(choices=[('not_available', 'Not Available'), ('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], max_length=50)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
