# Generated by Django 5.0.1 on 2024-02-26 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connector', '0002_alter_pet_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='news',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
