name: Paws Together Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONPATH: ${{ github.workspace }}/paws_together_backend
  DJANGO_SETTINGS_MODULE: paws_together_backend.settings
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:

    environment: pawsappenv
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Database
      run: |
        sudo apt-get -yqq install libpq-dev
        python manage.py makemigrations
        python manage.py migrate
      working-directory: ./paws_together_backend
    - name: Run tests
      run: |
        python manage.py test
      working-directory: ./paws_together_backend